"""Training runner: manages training scripts across platform sessions."""

import os
import json
import time
import subprocess
import logging
from pathlib import Path
from typing import Optional

from session import Session, SessionManager
from platforms import PlatformConfig

logger = logging.getLogger("free-gpu-trainer")


class TrainingJob:
    """Represents a training job that can span multiple sessions."""

    def __init__(self, script_path: str, checkpoint_dir: str = "./checkpoints",
                 resume: bool = True):
        self.script_path = script_path
        self.checkpoint_dir = Path(checkpoint_dir)
        self.resume = resume
        self.total_epochs: int = 0
        self.completed_epochs: int = 0
        self.current_loss: float = 0.0
        self.best_loss: float = float('inf')
        self._process: Optional[subprocess.Popen] = None
        self._state_file = self.checkpoint_dir / "training_state.json"

    def save_state(self):
        """Save training state for resume after rotation."""
        self.checkpoint_dir.mkdir(parents=True, exist_ok=True)
        state = {
            "script": self.script_path,
            "total_epochs": self.total_epochs,
            "completed_epochs": self.completed_epochs,
            "current_loss": self.current_loss,
            "best_loss": self.best_loss,
            "last_checkpoint": time.time(),
        }
        with open(self._state_file, "w") as f:
            json.dump(state, f, indent=2)
        logger.info(f"Training state saved: {self.completed_epochs}/{self.total_epochs} epochs")

    def load_state(self) -> bool:
        """Load training state from previous session."""
        if not self._state_file.exists():
            return False
        try:
            with open(self._state_file) as f:
                state = json.load(f)
            self.completed_epochs = state.get("completed_epochs", 0)
            self.current_loss = state.get("current_loss", 0.0)
            self.best_loss = state.get("best_loss", float('inf'))
            logger.info(
                f"Training state loaded: resuming from epoch {self.completed_epochs}"
            )
            return True
        except Exception as e:
            logger.error(f"Failed to load training state: {e}")
            return False

    def generate_run_command(self, platform: PlatformConfig) -> str:
        """Generate the command to run the training script on a given platform.
        
        This creates a platform-specific wrapper that handles:
        - GPU setup
        - Checkpoint loading/saving
        - Environment configuration
        """
        resume_flag = ""
        if self.resume and self.checkpoint_dir.exists():
            resume_flag = f"--resume {self.checkpoint_dir}"

        # Platform-specific GPU setup
        gpu_setup = self._gpu_setup_commands(platform)

        cmd = f"""#!/bin/bash
# Auto-generated by free-gpu-trainer
# Platform: {platform.name} ({platform.gpu_type})
# Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}

{gpu_setup}

# Training script
python {self.script_path} \\
    --checkpoint-dir {self.checkpoint_dir} \\
    {resume_flag}

# Save state on exit
echo "Training session completed or interrupted"
"""
        return cmd

    def _gpu_setup_commands(self, platform: PlatformConfig) -> str:
        """Platform-specific GPU and environment setup."""
        setups = {
            "google_colab": """
# Colab: GPU already configured in runtime
# Ensure CUDA is available
python -c "import torch; print(f'CUDA: {torch.cuda.is_available()}, Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"N/A\"}')" 2>/dev/null || true
""",
            "kaggle": """
# Kaggle: Enable GPU in Settings > Accelerator
python -c "import torch; print(f'CUDA: {torch.cuda.is_available()}, Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"N/A\"}')" 2>/dev/null || true
""",
            "oracle_cloud": """
# Oracle Cloud: Install CUDA if needed
if ! command -v nvidia-smi &> /dev/null; then
    echo "Installing NVIDIA drivers..."
    sudo apt-get update && sudo apt-get install -y nvidia-driver-535
fi
""",
            "intel_devcloud": """
# Intel DevCloud: Use oneAPI
source /opt/intel/oneapi/setvars.sh 2>/dev/null || true
export ONEAPI_DEVICE_SELECTOR="gpu:*"
""",
            "default": """
# Generic GPU setup
python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')" 2>/dev/null || true
""",
        }
        return setups.get(platform.key, setups["default"])

    def generate_notebook_code(self, platform: PlatformConfig) -> str:
        """Generate Jupyter notebook cell code for notebook-based platforms."""
        resume_flag = ""
        if self.resume and self.checkpoint_dir.exists():
            resume_flag = f', resume_from="{self.checkpoint_dir}"'

        code = f"""# Auto-generated by free-gpu-trainer
# Platform: {platform.name} ({platform.gpu_type})
# Install dependencies if needed
!pip install -q torch torchvision transformers accelerate peft 2>/dev/null

import torch
print(f"GPU: {{torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'N/A'}}")
print(f"CUDA Available: {{torch.cuda.is_available()}}")

# Mount drive for checkpoints (Colab)
try:
    from google.colab import drive
    drive.mount('/content/drive')
    CHECKPOINT_DIR = '/content/drive/MyDrive/checkpoints'
except:
    CHECKPOINT_DIR = './checkpoints'

# Run training
!python {self.script_path} --checkpoint-dir {{CHECKPOINT_DIR}} {resume_flag}
"""
        return code
